### ISSUE TITLE
ERROR: cannot find name 'stringify...

### ISSUE THREAD

**Issue by uuidcode** [cincheo/jsweet#107]
run mvn jsweet:jseet with below java and maven, 
below warn and error is occured.
I don't understand why stringify is not found.

```
WARN: candy jquery:1.10.0-1.0.0-20160202 was generated for a different version of the transpiler (current:1.1.0, candy:1.0.0)
ERROR: cannot find name 'stringify' at ....../jsweet/js/Index.java(29)
[ERROR] transpilation failed
org.apache.maven.plugin.MojoFailureException: transpilation failed with 1 error(s) and 1 warning(s)
    at org.jsweet.AbstractJSweetMojo.transpile(AbstractJSweetMojo.java:304)
    at org.jsweet.JSweetMojo.execute(JSweetMojo.java:41)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
```

Index.java

``` java
import static def.jquery.Globals.$;
import static jsweet.dom.Globals.alert;
import static jsweet.dom.Globals.console;
import static jsweet.dom.Globals.document;
import static jsweet.lang.JSON.stringify;

import def.jquery.JQueryAjaxSettings;
import def.jquery.JQueryXHR;

public class Index {
    public void index() {
        $(document).ready(() -> {

            console.info("starting JQuery example");

            Project project = new Project();
            project.setName("Test");

            $("a").click(event -> {
                $.ajax(new JQueryAjaxSettings() {
                    {
                        this.url = "/api";
                        this.contentType = "application/json; charset=utf-8";
                        this.type = "POST";
                        this.data = stringify(project); // 29 line
                    }

                    public Object success(Object data, String textStatus, JQueryXHR jqXHR) {
                        console.log(data);
                        return data;
                    }
                });

                alert("Hello, World");
                $("body").append("<h1>" + project.getName() + "</h1>");
                event.preventDefault();
                return event;
            });

            return null;
        });
    }
}
```

pom.xml

``` xml
         <dependency>
            <groupId>org.jsweet.candies</groupId>
            <artifactId>jsweet-core</artifactId>
            <version>1.1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.jsweet.candies</groupId>
            <artifactId>jquery</artifactId>
            <version>1.10.0-1.0.0-20160202</version>
        </dependency>

...

        <plugin>
                <groupId>org.jsweet</groupId>
                <artifactId>jsweet-maven-plugin</artifactId>
                <version>1.1.0-SNAPSHOT</version>
                <configuration>
                    <outDir>src/main/webapp/js</outDir>
                    <targetVersion>ES5</targetVersion>
                    <declaration>false</declaration>
                    <bundle>true</bundle>
                    <bundlesDirectory>src/main/webapp/js</bundlesDirectory>
                    <includes>
                        <include>**/entity/*.java</include>
                        <include>**/js/*.java</include>
                    </includes>
                </configuration>
            </plugin>
```

**Comment by renaudpawlak** [comment]
The code in JSweet is meant to be as close as possible to TypeScript code. So, you should write:

```java
import static jsweet.lang.JSON;
...
this.data = JSON.stringify(project);
```

That said, doing an import static must work from a Java perspective. So let's call it a bug :). I will fix it ASAP. Thank you. That helps a lot of have feedback on alternate uses of the API.

**Comment by uuidcode** [comment]
Thanks for your quick response.
I got it how jsweet works.

**Comment by renaudpawlak** [comment]
Related to #66 and #54.
