### ISSUE TITLE
ERROR: type 'Function' is not generic

### ISSUE THREAD

**Issue by fedorov-s-n** [cincheo/jsweet#127]
To reproduce: clone jsweet-quickstart and change body to

    public static void main(String[] args) {
        Function function  = o->o;
        System.out.println("Hi, random=" + function.apply(4));
    }

It fails with
ERROR: type 'Function' is not generic at jsweet-quickstart/src/main/java/quickstart/QuickStart.java(13)
transpilation failed
org.apache.maven.plugin.MojoFailureException: transpilation failed with 1 error(s) and 3 warning(s)
	at org.jsweet.AbstractJSweetMojo.transpile(AbstractJSweetMojo.java:303)
	at org.jsweet.JSweetMojo.execute(JSweetMojo.java:41)
        ...

It's enough to change `Function` to `Function<Object,Object>` to transpile that.

**Comment by fedorov-s-n** [comment]
Another one:

        Deque<String> deque = new LinkedList();


ERROR: type 'LinkedList<{}>' is not assignable to type 'Deque<string>'
