### ISSUE TITLE
NullPointerException during translation

### ISSUE THREAD

**Issue by nbransby** [cincheo/jsweet#185]
Is there a way to enable debugging output to know what file it is having a problem with? This was from jsweet built from commit c64b3e6c6188a3d15116e3546c0449a2cb863a75

Caused by: java.lang.NullPointerException
        at org.jsweet.transpiler.typescript.Java2TypeScriptTranslator.visitApply(Java2TypeScriptTranslator.java:2201)
        at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
        at org.jsweet.transpiler.util.AbstractTreeScanner.scan(AbstractTreeScanner.java:148)
        at org.jsweet.transpiler.util.AbstractTreePrinter.print(AbstractTreePrinter.java:118)
        at org.jsweet.transpiler.typescript.Java2TypeScriptTranslator.visitApply(Java2TypeScriptTranslator.java:2312)
        at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
        at org.jsweet.transpiler.util.AbstractTreeScanner.scan(AbstractTreeScanner.java:148)
        at org.jsweet.transpiler.util.AbstractTreePrinter.print(AbstractTreePrinter.java:118)
        at org.jsweet.transpiler.typescript.Java2TypeScriptTranslator.visitReturn(Java2TypeScriptTranslator.java:3004)
        at com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1384)
        at org.jsweet.transpiler.util.AbstractTreeScanner.scan(AbstractTreeScanner.java:148)
        at org.jsweet.transpiler.util.AbstractTreePrinter.print(AbstractTreePrinter.java:118)
        at org.jsweet.transpiler.typescript.Java2TypeScriptTranslator.visitCase(Java2TypeScriptTranslator.java:3189)
        at com.sun.tools.javac.tree.JCTree$JCCase.accept(JCTree.java:1113)
        at org.jsweet.transpiler.util.AbstractTreeScanner.scan(AbstractTreeScanner.java:148)
        at org.jsweet.transpiler.util.AbstractTreePrinter.print(AbstractTreePrinter.java:118)
        at org.jsweet.transpiler.typescript.Java2TypeScriptTranslator.visitSwitch(Java2TypeScriptTranslator.java:3168)
        at com.sun.tools.javac.tree.JCTree$JCSwitch.accept(JCTree.java:1087)
        at org.jsweet.transpiler.util.AbstractTreeScanner.scan(AbstractTreeScanner.java:148)
        at org.jsweet.transpiler.util.AbstractTreePrinter.print(AbstractTreePrinter.java:118)
        at org.jsweet.transpiler.typescript.Java2TypeScriptTranslator.printBlockStatement(Java2TypeScriptTranslator.java:1665)
        at org.jsweet.transpiler.typescript.Java2TypeScriptTranslator.printBlockStatements(Java2TypeScriptTranslator.java:1658)
        at org.jsweet.transpiler.typescript.Java2TypeScriptTranslator.visitMethodDef(Java2TypeScriptTranslator.java:1508)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
        at org.jsweet.transpiler.util.AbstractTreeScanner.scan(AbstractTreeScanner.java:148)
        at org.jsweet.transpiler.util.AbstractTreePrinter.print(AbstractTreePrinter.java:118)
        at org.jsweet.transpiler.typescript.Java2TypeScriptTranslator.visitClassDef(Java2TypeScriptTranslator.java:912)
        at org.jsweet.transpiler.typescript.Java2TypeScriptTranslator.visitClassDef(Java2TypeScriptTranslator.java:1022)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:693)
        at org.jsweet.transpiler.util.AbstractTreeScanner.scan(AbstractTreeScanner.java:148)
        at org.jsweet.transpiler.util.AbstractTreePrinter.print(AbstractTreePrinter.java:118)
        at org.jsweet.transpiler.typescript.Java2TypeScriptTranslator.visitClassDef(Java2TypeScriptTranslator.java:1039)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:693)
        at org.jsweet.transpiler.util.AbstractTreeScanner.scan(AbstractTreeScanner.java:148)
        at org.jsweet.transpiler.util.AbstractTreePrinter.print(AbstractTreePrinter.java:118)
        at org.jsweet.transpiler.typescript.Java2TypeScriptTranslator.visitTopLevel(Java2TypeScriptTranslator.java:588)
        at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518)
        at org.jsweet.transpiler.util.AbstractTreeScanner.scan(AbstractTreeScanner.java:148)
        at org.jsweet.transpiler.util.AbstractTreePrinter.print(AbstractTreePrinter.java:118)
        at org.jsweet.transpiler.JSweetTranspiler.generateTsFiles(JSweetTranspiler.java:739)
        at org.jsweet.transpiler.JSweetTranspiler.java2ts(JSweetTranspiler.java:708)
        at org.jsweet.transpiler.JSweetTranspiler.transpile(JSweetTranspiler.java:682)
        at org.jsweet.gradle.JSweetTranspileTask.transpile(JSweetTranspileTask.java:126)
        ... 76 more

**Comment by renaudpawlak** [comment]
I have just commited an improvement that reports sound errors when the transpiler crashes (similarly to the crash you report here). So if you run the 1.2.0-SNAPSHOT version, you should see where the problem is (and eventually tell us what the core problem is).

**Comment by nbransby** [comment]
Thanks, latest build appears not to be crashing now anyway

**Comment by renaudpawlak** [comment]
Oh. Ok. Well, at least we have better error report in case it happens again ;)

**Comment by nbransby** [comment]
I believe it was a function inside an enumeration that was the issue
