### ISSUE TITLE
Enums that implement an interface blow up on transpile

### ISSUE THREAD

**Issue by StormeHawke** [cincheo/jsweet#269]
Consider the following simple case:

```java
public enum DayOfWeek implements SomeInterface {
    Sunday(0),
    Monday(1),
    Tuesday(2),
    Wednesday(3),
    Thursday(4),
    Friday(5),
    Saturday(6);

    public final int persistenceValue;

    DayOfWeek(int persistenceValue) {
        this.persistenceValue = persistenceValue;
    }
}
```

Any interface will cause the problem, with or without methods that need overriding:

```java
public interface SomeInterface {
}
```

When attempting to transpile TS to JS with the above class, I get the following error output:
```
2017-05-10 11:10:35.035 INFO  JSweetTranspiler:1121 - launching tsc...
2017-05-10 11:10:35.035 DEBUG ProcessUtil:181 - run command: /Users/brian.trezise/.jsweet-node_modules/bin/tsc --target ES5 --experimentalDecorators --sourceMap --rootDir /Users/brian.trezise/git/workforce-management-api-contract/target/ts --outDir /Users/brian.trezise/git/workforce-management-api-contract/target/js .tsc-rootfile.ts bundle.ts ../../.jsweet/candies/typings/src/typings/j4ts/0.4.0/.tsc-rootfile.d.ts ../../.jsweet/candies/typings/src/typings/j4ts/0.4.0/bundle.d.ts
2017-05-10 11:10:36.036 INFO  JSweetTranspiler:1132 - bundle.ts(259,27): error TS1005: '{' expected.
2017-05-10 11:10:36.036 ERROR output:46 - '{' expected at /Users/brian.trezise/git/workforce-management-api-contract/src/main/java/com/inin/wfm/api/constants/DayOfWeek.java(3)
2017-05-10 11:10:36.036 INFO  JSweetTranspiler:1132 - bundle.ts(259,38): error TS1005: ';' expected.
2017-05-10 11:10:36.036 ERROR output:46 - ';' expected at /Users/brian.trezise/git/workforce-management-api-contract/src/main/java/com/inin/wfm/api/constants/DayOfWeek.java(3)
2017-05-10 11:10:36.036 INFO  JSweetTranspiler:1132 - bundle.ts(259,79): error TS1005: ';' expected.
2017-05-10 11:10:36.036 ERROR output:46 - ';' expected at /Users/brian.trezise/git/workforce-management-api-contract/src/main/java/com/inin/wfm/api/constants/DayOfWeek.java(3)
2017-05-10 11:10:38.038 INFO  JSweetTranspiler:721 - transpilation process finished in 4408 ms
[ERROR] transpilation failed
org.apache.maven.plugin.MojoFailureException: transpilation failed with 3 error(s) and 1 warning(s)
	at org.jsweet.AbstractJSweetMojo.transpile(AbstractJSweetMojo.java:337)
	at org.jsweet.JSweetMojo.execute(JSweetMojo.java:41)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```
We have several enums similar to this because our persistence layer saves the ordinal value whilst our api wants the string values, and I don't want to directly depend on the built-in enum ordinal as I consider that dangerous and unwise.

I have written an external utility class to translate from ordinal to String as JSweet doesn't appear to be able to handle iterating over `Enum.values()` nor can I seem to pre-populate a static map to cache the values, but that utility currently relies on reflection to get the ordinal value, which is less than ideal.   Note that this utility is excluded from transpilation as we only care about it on the jvm side.

There are several possible fixes that would be helpful here, I'll list them in order from "top preference" to "it's an improvement":

1. Allow me to statically populate a static map of values, similar to 
```java
    private final static Map<Integer, DayOfWeek> ORDINAL_MAP = new HashMap<>();
    static {
        for (DayOfWeek c : values()) {
            ORDINAL_MAP.put(c.backEndOrdinal, c);
        }
    }

    public static DayOfWeek fromPersistenceValue(Integer value) {
        return ORDINAL_MAP.get(value);
    }
```
2. Support  `.values()` so I can iterate over that
3. Don't break when an enum implements an interface (even if only by outputting a warning that it's not supported and skipping the interface portion, in this case the TS/JS code doesn't care about the ordinals anyway)

**Comment by renaudpawlak** [comment]
Unless I missed something, it should be all working with v2.0.0-SNAPSHOT (master).

**Comment by StormeHawke** [comment]
Thanks!
