### ISSUE TITLE
Nodejs under Ubuntu 16.4 (Unknown tsc error)

### ISSUE THREAD

**Issue by asocjal** [cincheo/jsweet#316]
Hi,

I discovered jsweet few weeks ago. For me this is really great, as I don't know JS very well. Under Windows everything work great, but now, I'm trying to use it under Ubuntu and have troubles.

Don't know if this is issue or my ignorance (I'm rather newbie Ubuntu user).

After install plugin I've got error message:
"cannot find Node.js: install first and make sure that the 'node' command is in your execution path"

After that I installed nodejs using command "sudo apt-get install nodejs". After that jsweet still cannot find "node" command, because executable is named "nodejs" (inside /usr/bin). I just renamed "nodejs" to "node".

After that I've got other error message: "Unknown tsc error".

I tried to solve it other way. I downloaded nodejs from https://nodejs.org/en/download/ and extracted to some directory. Next I make link of bin/node and put this ling to /usr/bin under "node" name. After that, I have still the same error from jsweet "Unknown tsc error". When I run "node" from console, it seems t work.

Here is stack trace:
`java.io.IOException: Cannot run program "npm" (in directory "/root"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.jsweet.transpiler.util.ProcessUtil.runCommand(ProcessUtil.java:193)
	at org.jsweet.transpiler.util.ProcessUtil.installNodePackage(ProcessUtil.java:257)
	at org.jsweet.transpiler.JSweetTranspiler.initNode(JSweetTranspiler.java:291)
	at org.jsweet.transpiler.JSweetTranspiler.transpile(JSweetTranspiler.java:694)
	at org.jsweet.plugin.builder.JSweetBuilder.transpileFiles(JSweetBuilder.java:575)
	at org.jsweet.plugin.builder.JSweetBuilder.fullBuild(JSweetBuilder.java:618)
	at org.jsweet.plugin.builder.JSweetBuilder.build(JSweetBuilder.java:520)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 19 more
2017-06-30 13:52:24.024 ERROR ProcessUtil:235 - Cannot run program "/root/.jsweet-node_modules/bin/tsc" (in directory "/home/usr/git/LnMonitor/WebClient/.generated"): error=2, No such file or directory
java.io.IOException: Cannot run program "/root/.jsweet-node_modules/bin/tsc" (in directory "/home/usr/git/LnMonitor/WebClient/.generated"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.jsweet.transpiler.util.ProcessUtil.runCommand(ProcessUtil.java:193)
	at org.jsweet.transpiler.JSweetTranspiler.runTSC(JSweetTranspiler.java:1131)
	at org.jsweet.transpiler.JSweetTranspiler.ts2js(JSweetTranspiler.java:1122)
	at org.jsweet.transpiler.JSweetTranspiler.transpile(JSweetTranspiler.java:714)
	at org.jsweet.plugin.builder.JSweetBuilder.transpileFiles(JSweetBuilder.java:575)
	at org.jsweet.plugin.builder.JSweetBuilder.fullBuild(JSweetBuilder.java:618)
	at org.jsweet.plugin.builder.JSweetBuilder.build(JSweetBuilder.java:520)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 19 more
2017-06-30 13:52:25.025 ERROR ProcessUtil:235 - Cannot run program "npm" (in directory "/root"): error=2, No such file or directory
java.io.IOException: Cannot run program "npm" (in directory "/root"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.jsweet.transpiler.util.ProcessUtil.runCommand(ProcessUtil.java:193)
	at org.jsweet.transpiler.util.ProcessUtil.installNodePackage(ProcessUtil.java:257)
	at org.jsweet.transpiler.JSweetTranspiler.initNode(JSweetTranspiler.java:291)
	at org.jsweet.transpiler.JSweetTranspiler.transpile(JSweetTranspiler.java:694)
	at org.jsweet.plugin.builder.JSweetBuilder.transpileFiles(JSweetBuilder.java:575)
	at org.jsweet.plugin.builder.JSweetBuilder.fullBuild(JSweetBuilder.java:618)
	at org.jsweet.plugin.builder.JSweetBuilder.build(JSweetBuilder.java:520)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 19 more
2017-06-30 13:52:25.025 ERROR ProcessUtil:235 - Cannot run program "/root/.jsweet-node_modules/bin/tsc" (in directory "/home/usr/git/LnMonitor/WebClient/.generated"): error=2, No such file or directory
java.io.IOException: Cannot run program "/root/.jsweet-node_modules/bin/tsc" (in directory "/home/usr/git/LnMonitor/WebClient/.generated"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.jsweet.transpiler.util.ProcessUtil.runCommand(ProcessUtil.java:193)
	at org.jsweet.transpiler.JSweetTranspiler.runTSC(JSweetTranspiler.java:1131)
	at org.jsweet.transpiler.JSweetTranspiler.ts2js(JSweetTranspiler.java:1122)
	at org.jsweet.transpiler.JSweetTranspiler.transpile(JSweetTranspiler.java:714)
	at org.jsweet.plugin.builder.JSweetBuilder.transpileFiles(JSweetBuilder.java:575)
	at org.jsweet.plugin.builder.JSweetBuilder.fullBuild(JSweetBuilder.java:618)
	at org.jsweet.plugin.builder.JSweetBuilder.build(JSweetBuilder.java:520)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 19 more
`
The same issue when just do this under Ubuntu:
http://www.jsweet.org/getting-started/

Please help!

**Comment by renaudpawlak** [comment]
Umm... I wish I could help... but it looks more like a node.js installation issue. If it can help, for me JSweet works fine with Debian 3.2.68-1+deb7u4.
