### ISSUE TITLE
Maven plugin error in RC1

### ISSUE THREAD

**Issue by Eclesia** [cincheo/jsweet#330]
Hello, 
I had this error with the latest 2.0.0-rc1 build.

```
[INFO] JSweet transpiler version 2.0.0-rc1 (build date: 2017-08-02 18:25:10)
[ERROR] failed to create transpiler
java.lang.NullPointerException
	at org.jsweet.AbstractJSweetMojo.logInfo(AbstractJSweetMojo.java:133)
	at org.jsweet.AbstractJSweetMojo.getCandiesJars(AbstractJSweetMojo.java:335)
	at org.jsweet.AbstractJSweetMojo.createJSweetTranspiler(AbstractJSweetMojo.java:172)
	at org.jsweet.JSweetMojo.execute(JSweetMojo.java:39)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
```

**Comment by renaudpawlak** [comment]
See https://github.com/lgrignon/jsweet-maven-plugin/issues/29
Try Maven plugin version 2.0.0-rc1u1
