### ISSUE TITLE
Cannot cast to `char` in case statements

### ISSUE THREAD

**Issue by blagae** [cincheo/jsweet#433]
I cannot cast character literals or numbers to the `char` type, but I am allowed cast to `int`. I would expect either all to succeed or all to fail (preferably the former). In the below code, only the last two case statements will fail:

```java
RuntimeException fail = new RuntimeException("fail"); // SSCCE !
char x = 'a';
switch (x) {
    case 96:  return;
    case (int) 97: return;
    case (int) 'b': return;
    case (char) 'c': throw fail;
    case (char) 100: throw fail;
}
```

Below is the full stack trace, which is very informative:

```2018-05-08 14:59:31.031 ERROR output:55 - internal transpiler error at C:\jsweet-quickstart\src\main\java\quickstart\QuickStart.java(30)
dumping transpiler's strack trace:
   [JCCase] case (char)'c': 
... (C:\jsweet-quickstart\src\main\java\quickstart\QuickStart.java:30)
   [JCSwitch] switch (x) {
... (C:\jsweet-quickstart\src\main\java\quickstart\QuickStart.java:23)
   [JCBlock] {
... (C:\jsweet-quickstart\src\main\java\quickstart\QuickStart.java:19)
   [JCMethodDecl] public static void main(String... (C:\jsweet-quickstart\src\main\java\quickstart\QuickStart.java:19)
   [JCClassDecl] public class QuickStart {
... (C:\jsweet-quickstart\src\main\java\quickstart\QuickStart.java:17)
   [JCCompilationUnit] package quickstart;
... (C:\jsweet-quickstart\src\main\java\quickstart\QuickStart.java:1)
java.lang.ClassCastException: com.sun.tools.javac.tree.JCTree$JCTypeCast cannot be cast to com.sun.tools.javac.tree.JCTree$JCLiteral
	at org.jsweet.transpiler.Java2TypeScriptTranslator.visitCase(Java2TypeScriptTranslator.java:4831)
	at com.sun.tools.javac.tree.JCTree$JCCase.accept(JCTree.java:1113)
	at org.jsweet.transpiler.util.AbstractTreeScanner.scan(AbstractTreeScanner.java:236)
	at org.jsweet.transpiler.util.AbstractTreePrinter.print(AbstractTreePrinter.java:125)
	at org.jsweet.transpiler.Java2TypeScriptTranslator.visitSwitch(Java2TypeScriptTranslator.java:4803)
	at com.sun.tools.javac.tree.JCTree$JCSwitch.accept(JCTree.java:1087)
	at org.jsweet.transpiler.util.AbstractTreeScanner.scan(AbstractTreeScanner.java:236)
	at org.jsweet.transpiler.util.AbstractTreePrinter.print(AbstractTreePrinter.java:125)
	at org.jsweet.transpiler.Java2TypeScriptTranslator.printBlockStatement(Java2TypeScriptTranslator.java:2727)
	at org.jsweet.transpiler.Java2TypeScriptTranslator.printBlockStatements(Java2TypeScriptTranslator.java:2720)
	at org.jsweet.transpiler.Java2TypeScriptTranslator.visitMethodDef(Java2TypeScriptTranslator.java:2393)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
	at org.jsweet.transpiler.util.AbstractTreeScanner.scan(AbstractTreeScanner.java:236)
	at org.jsweet.transpiler.util.AbstractTreePrinter.print(AbstractTreePrinter.java:125)
	at org.jsweet.transpiler.Java2TypeScriptTranslator.visitClassDef(Java2TypeScriptTranslator.java:1601)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:693)
	at org.jsweet.transpiler.util.AbstractTreeScanner.scan(AbstractTreeScanner.java:236)
	at org.jsweet.transpiler.util.AbstractTreePrinter.print(AbstractTreePrinter.java:125)
	at org.jsweet.transpiler.Java2TypeScriptTranslator.visitTopLevel(Java2TypeScriptTranslator.java:872)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518)
	at org.jsweet.transpiler.util.AbstractTreeScanner.scan(AbstractTreeScanner.java:236)
	at org.jsweet.transpiler.util.AbstractTreePrinter.print(AbstractTreePrinter.java:125)
	at org.jsweet.transpiler.JSweetTranspiler.generateTsFiles(JSweetTranspiler.java:988)
	at org.jsweet.transpiler.JSweetTranspiler.java2ts(JSweetTranspiler.java:955)
	at org.jsweet.transpiler.JSweetTranspiler.transpile(JSweetTranspiler.java:912)
	at org.jsweet.AbstractJSweetMojo.transpile(AbstractJSweetMojo.java:422)
	at org.jsweet.JSweetMojo.execute(JSweetMojo.java:41)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)```

**Comment by blagae** [comment]
Outside of cast statements, this will also work fine: `char x = (char) 97;`

**Comment by lgrignon** [comment]
Should be ok now, please see test case: https://github.com/cincheo/jsweet/blob/master/transpiler/src/test/java/source/api/Characters.java

If this is ok for you, could you please close this issue.

**Comment by blagae** [comment]
This fix indeed solved my problem
