### ISSUE TITLE
Eclipse-Plugin does not compile jsweet-quickstart in Eclipse Photon on MacOS

### ISSUE THREAD

**Issue by frank-engelen** [cincheo/jsweet#462]
I have cloned the jsweet-quickstart project and imported it as a maven project into a fresh installation of Eclipse Photon + JSweet-Eclipse Plugin. 

I followed https://github.com/cincheo/jsweet-eclipse-plugin "How to start from the quick start project" but no js or ts files are generated (maven generate-sources works!).

In the Eclipse-Error Log I see the following stacktrace:

Message: cannot compile
ava.lang.NoSuchFieldError: CLASSPATH
	at org.jsweet.transpiler.JSweetTranspiler.initJavac(JSweetTranspiler.java:486)
	at org.jsweet.transpiler.JSweetTranspiler.setupCompiler(JSweetTranspiler.java:795)
	at org.jsweet.transpiler.JSweetTranspiler.java2ts(JSweetTranspiler.java:892)
	at org.jsweet.transpiler.JSweetTranspiler.transpile(JSweetTranspiler.java:875)
	at org.jsweet.plugin.builder.JSweetBuilder.transpileFiles(JSweetBuilder.java:542)
	at org.jsweet.plugin.builder.JSweetBuilder.fullBuild(JSweetBuilder.java:585)
	at org.jsweet.plugin.builder.JSweetBuilder.build(JSweetBuilder.java:487)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:795)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)

eclipse.buildId=4.8.0.I20180611-0500
java.version=10
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_DE
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/frank/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -keyring /Users/frank/.eclipse_keyring

Mac High Sierra, Version 10.13.5

It is not easy to set environment vars for GUI-Applications in MacOS so it would be very nice if the
plugin could work without.

Thank you/Regards,
Frank

**Comment by lgrignon** [comment]
Hi. JSweet does not support version 10 for now.
Please downgrade to Java 8 if possible.

If you ever want to add this support, we would be glad to merge your contribution

**Comment by frank-engelen** [comment]
Thank you very much for the reply. It works with Java 8 :)
