### ISSUE TITLE
Transpiling org.apache.logging.log4j.Logger to typescript-logging stile

### ISSUE THREAD

**Issue by courteous** [cincheo/jsweet#468]
Hello Renaud, Louis, 

First of all many thanks for your work put into this transpilter!!!

I have a fairly standard question here but i was not able to find an answer in the "JSweet Language Specifications" documentation thus asking it. 

in my java code i have multiple classes that have the following construct

```
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class Type {
...
    private final static Logger logger = LogManager.getLogger(Type.class.getName()); 


	@Override
	public Logger getLogger() {
		return Type.logger;
	}

}
```

I am using the standard log4j library. 

Now when i transpile this to TS only I get 

```
export class Type {

    static __primitive_elements_Type_logger : Logger; public static __primitive_elements_Type_logger_$LI$() : Logger { if(Type.__primitive_elements_Type_logger == null) Type.__primitive_elements_Type_logger = LogManager.getLogger(/* getName */(c => c["__class"]?c["__class"]:c["name"])(Type)); return Type.__primitive_elements_Type_logger; };


    public getLogger() : Logger {
        return Type.__primitive_elements_Type_logger_$LI$();
    }
}
```

I would like to use a solution called typescript-logging i.e. 
[typescript-logging](https://www.npmjs.com/package/typescript-logging)

I usually use the typescript logging  like that:

```
import { factory } from "../../../../ConfigLog4j";
const LOGGER = factory.getLogger("Type");
import { Logger } from 'typescript-logging';


export class Type {

  ...
    public getLogger() : Logger {
        return LOGGER;
    }
    
}
```

Now at first i wanted to do that with an Adapter, but it seems that adapters are only working out of the box for jdk classes , i.e. for classes outside of the jdk I am getting "java.lang.RuntimeException: java.lang.reflect.InvocationTargetException". 

So my question is what is the best way to go here in order to solve that problem. 

here is  what i already tired  i.e  similar example below worked for the long and ByteBuffer classes from the standart jdk.

```
public class LogManagerAdapter  extends PrinterAdapter	{

	boolean firstTime = true;
	
	
	public LogManagerAdapter(PrinterAdapter context) {
		super(context);

		addTypeMapping(org.apache.logging.log4j.LogManager.class.getName(), "LogManager");
		System.out.println("LogManager addTypeMapping hit.");
	}

	
	
	@Override
	public boolean substituteNewClass(NewClassElement newClass) {

		String className = newClass.getTypeAsElement().toString();
		
		if (LogManager.class.getName().equals(className)) {

			print("LogManager(").printArgList(newClass.getArguments()).print(")");
			
			insertHeader();
			return true;
		}
		// delegate to the adapter chain
		return super.substituteNewClass(newClass);
	}
	
	
	
	
	@Override
	public boolean substituteMethodInvocation(MethodInvocationElement invocation) {
		if (invocation.getTargetExpression() != null) {
			Element targetType = invocation.getTargetExpression().getTypeAsElement();
			System.out.println("LogManager substituteMethodInvocation hit.");

		}
		// delegate to the adapter chain
		return super.substituteMethodInvocation(invocation);
	}
	

	@Override
	public boolean substituteAssignment(AssignmentElement assignment) {
	
		if( super.getParentAdapter() == null ) {
			return false;
		}else {
			insertHeader();
			return super.getParentAdapter().substituteAssignment(assignment);
		}
	}

	

	@Override
	public String needsImport(ImportElement importElement, String qualifiedName) {


		String result;
		if( super.getParentAdapter() == null) {
			

			if (importElement.getImportedType() == null) {
				System.out.println("importElement.getImportedType() is NULL");
				result = null;
				
			}
			else {
				result = getRootRelativeName(importElement.getImportedType());
				System.out.println("get root relative name is1: " + result);
			} 
					
		}else {
			result = super.getParentAdapter().needsImport(importElement, qualifiedName);
			System.out.println("get root relative name is2: " + result);

			
				if (result != null && result.contains("LogManager")) {
					System.out.println("LogManager needsImport hit: " + result);
					
					System.out.println("ImportElement is:" + importElement.getImportedType().toString());
					System.out.println("QualifiedName is:" + qualifiedName);
					
					String toReturn = "LogManager";
					return toReturn;
				}
				
			}
		
		return result;
				
				
	}
	
	
	
	@Override
	public void afterType(TypeElement type) {
		firstTime = true;
	}	

	private void insertHeader(){
		if (firstTime){

			String importHeader1 = "const LOGGER = factory.getLogger(\"Type\"); \n";
			String importHeader2 = "import { Logger } from 'typescript-logging'; \n";
			
			String combined = importHeader1 + importHeader2;
			
			addHeader("org.apache.logging.log4j.LogManager", combined);
			firstTime = false;
		}
	}

```	
	
		
	
}

but i am getting the following exception here. 

```
[ERROR] transpilation failed
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.jsweet.transpiler.JSweetFactory.createAdapter(JSweetFactory.java:113)
	at org.jsweet.transpiler.JSweetTranspiler.initJavac(JSweetTranspiler.java:594)
	at org.jsweet.transpiler.JSweetTranspiler.setupCompiler(JSweetTranspiler.java:907)
	at org.jsweet.transpiler.JSweetTranspiler.java2ts(JSweetTranspiler.java:1005)
	at org.jsweet.transpiler.JSweetTranspiler.transpile(JSweetTranspiler.java:988)
	at org.jsweet.AbstractJSweetMojo.transpile(AbstractJSweetMojo.java:445)
	at org.jsweet.JSweetMojo.execute(JSweetMojo.java:41)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jsweet.transpiler.JSweetFactory.createAdapter(JSweetFactory.java:89)
	... 28 more
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at LogManagerAdapter.<init>(LogManagerAdapter.java:29)
	... 33 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 34 more
```

My question is what would be the best way to go and solve this problem i.e. i do not seems to find a suitable candy for it, thus need to use the adapter,  but that does not work as well for me or i am programming it wrong.

**Comment by renaudpawlak** [comment]
The error looks quite explicit to me. The transpiler does not now the ``LogManager`` class. So, you need to add it to your classpath during transpilation. Just edit your ``pom.xml`` file to do so.

If you don't want to add it to you classpath, you can just replace ``org.apache.logging.log4j.LogManager.class.getName()`` with ``"org.apache.logging.log4j.LogManager"`` in your constructor (LogManagerAdapter.java:29). Then the adapter will work without having to know the ``LogManager`` class (less type-safe but ok).

**Comment by courteous** [comment]
Hello Renaud, thank you for the replay. I do understand that i have a problem with the classpath, but what i am saing is that i have 4 another Adapters that are working however they replace only classes from the standart JDK. I do use maven. If i do mvn eclipse:eclipse all is completing succesefully. However if i call the mvn jsweet:jsweet then  it seems that the pluggin can not find something that has been explicitly enabled in maven as a dependency i.e.    ```

	
	<dependency>
		<groupId>org.apache.logging.log4j</groupId>
		<artifactId>log4j-api</artifactId>
	</dependency>
	
	<dependency>
		<groupId>org.apache.logging.log4j</groupId>
		<artifactId>log4j-core</artifactId>
	</dependency>
	
``` 

thus i was hoping to find check if you guys have seen this problem before.

**Comment by renaudpawlak** [comment]
Probably the dependency should be declared in the JSweet plugin (not in the project dependencies). Move it in the plugin section and see what happens.
