### ISSUE TITLE
Plug-in error cant open yaml on eclips

### ISSUE THREAD

**Issue by shamwoo** [cincheo/jsweet#522]
eclipse.buildId=4.11.0.I20190307-0500
java.version=1.8.0_201
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.php.product -data file:/C:/Users/BeafStew/eclipse-workspace/ -product org.eclipse.epp.package.php.product

org.eclipse.lsp4e
Error
Fri Apr 19 23:19:54 EDT 2019
Unable to start language server: YAML Language Server: org.eclipse.wildwebdeveloper.yaml.YAMLLanguageServer@8a2f7e46

java.io.IOException: Unable to start language server: YAML Language Server: org.eclipse.wildwebdeveloper.yaml.YAMLLanguageServer@8a2f7e46
	at org.eclipse.lsp4e.server.ProcessStreamConnectionProvider.start(ProcessStreamConnectionProvider.java:44)
	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:194)
	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:564)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLanguageServers(LanguageServiceAccessor.java:516)
	at org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$1.run(ConnectDocumentToLanguageServerSetupParticipant.java:50)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by lgrignon** [comment]
Hello, thanks for reporting. This issue has been moved to the JSweet Eclipse plugin repo
