### ISSUE TITLE
Using Jsweet to convert an Applet to Java Script. A null pointer exception was thrown during the conversion

### ISSUE THREAD

**Issue by xeccgtt** [cincheo/jsweet#564]
We are try to convert an applet to Java Script.  A null pointer exception was thrown during the conversion.  I obscured our source code file name.  

2020-02-24 16:06:09.009 ERROR output:55 - internal transpiler error at Obscured_File_Name.java(315)
dumping transpiler's strack trace:
   [JCMethodDecl] public String getParameter(fin... (Obscured_File_Name.java(315,5))
   [JCClassDecl] public class Map extends Exten... (Obscured_File_Name.java(41,1))
... (Obscured_File_Name.java(22,1))
java.lang.NullPointerException
        at org.jsweet.transpiler.Java2TypeScriptTranslator.visitMethod(Java2TypeScriptTranslator.java:2175)
        at org.jsweet.transpiler.Java2TypeScriptTranslator.visitMethod(Java2TypeScriptTranslator.java:2239)
        at org.jsweet.transpiler.Java2TypeScriptTranslator.visitMethod(Java2TypeScriptTranslator.java:146)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.jsweet.transpiler.util.AbstractTreeScanner.scan(AbstractTreeScanner.java:269)
        at org.jsweet.transpiler.util.AbstractTreePrinter.print(AbstractTreePrinter.java:121)
        at org.jsweet.transpiler.Java2TypeScriptTranslator.visitClass(Java2TypeScriptTranslator.java:1746)
        at org.jsweet.transpiler.Java2TypeScriptTranslator.visitClass(Java2TypeScriptTranslator.java:146)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.jsweet.transpiler.util.AbstractTreeScanner.scan(AbstractTreeScanner.java:269)
        at org.jsweet.transpiler.util.AbstractTreePrinter.print(AbstractTreePrinter.java:121)
        at org.jsweet.transpiler.Java2TypeScriptTranslator.visitCompilationUnit(Java2TypeScriptTranslator.java:858)
        at org.jsweet.transpiler.Java2TypeScriptTranslator.visitCompilationUnit(Java2TypeScriptTranslator.java:146)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.jsweet.transpiler.util.AbstractTreeScanner.scan(AbstractTreeScanner.java:269)
        at org.jsweet.transpiler.util.AbstractTreePrinter.print(AbstractTreePrinter.java:121)
        at org.jsweet.transpiler.JSweetTranspiler.generateTsFiles(JSweetTranspiler.java:880)
        at org.jsweet.transpiler.JSweetTranspiler.java2ts(JSweetTranspiler.java:843)
        at org.jsweet.transpiler.JSweetTranspiler.transpile(JSweetTranspiler.java:771)
        at org.jsweet.AbstractJSweetMojo.transpile(AbstractJSweetMojo.java:606)
        at org.jsweet.JSweetMojo.execute(JSweetMojo.java:43)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
2020-02-24 16:06:10.010 INFO  JSweetTranspiler:903 - output file: Obscured_File_Name.ts
2020-02-24 16:06:10.010 INFO  JSweetTranspiler:928 - created Obscured_File_Name.ts

**Comment by lgrignon** [comment]
Hello,

Thanks for reporting.

Which version of JSweet are you using? Could you please provide a small repro project please (repo or zip)?

**Comment by lgrignon** [comment]
@xeccgtt any news on this?

**Comment by xeccgtt** [comment]
I have not proceeded any further with jsweet because of the null pointer exception.   I tried jsweet about a month ago and I believe we were using the latest version at  thattime.


Sincerely

Albert Stark

**Comment by lgrignon** [comment]
I think this is a JSweet 3 pre release bug which will be fixed soon. I keep it open

**Comment by lgrignon** [comment]
Hello again @xeccgtt 
3.0.0-RC4 has been deployed (and maven plugin is up to date) if you want to give it a shot
Warning : if you declare jsweet-core as a dependency, groupId is now `<groupId>org.jsweet.v3</groupId>`

I hope it will work for you 🤞

**Comment by lgrignon** [comment]
3.0.0-RC5 is deployed, please test it on this version if you can.
groupId is org.jsweet.v3 for almost all artifacts now (please see pom.xml & build.gradle here: https://github.com/cincheo/jsweet-examples)
