### ISSUE TITLE
NullPointerException during compilation in JSweetConfig and in CandyProcessor.checkCandyVersion when versions differ

### ISSUE THREAD

**Issue by AlexGeller1** [cincheo/jsweet#702]
Steps to reproduce
```bash
$ls ~/.m2/repository/org/jsweet/jsweet-maven-plugin
3.1.0  3.2.0-SNAPSHOT
$unzip jsweet-quickstart-master.zip
$cd jsweet-quickstart-master
$mvn generate-sources
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[[1;34mINFO[m] Scanning for projects...
[[1;33mWARNING[m] 
[[1;33mWARNING[m] Some problems were encountered while building the effective model for org.jsweet:jsweet-quickstart:jar:3.1.0
[[1;33mWARNING[m] 'version' contains an expression but should be a constant. @ org.jsweet:jsweet-quickstart:${jsweet.transpiler.version}, /home/alex/jsweet-bugs/bug1/pom.xml, line 6, column 11
[[1;33mWARNING[m] 
[[1;33mWARNING[m] It is highly recommended to fix these problems because they threaten the stability of your build.
[[1;33mWARNING[m] 
[[1;33mWARNING[m] For this reason, future Maven versions might no longer support building such malformed projects.
[[1;33mWARNING[m] 
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m--------------------< [0;36morg.jsweet:jsweet-quickstart[0;1m >--------------------[m
[[1;34mINFO[m] [1mBuilding JSweet quick start 3.1.0[m
[[1;34mINFO[m] [1m--------------------------------[ jar ]---------------------------------[m
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m--- [0;32mjsweet-maven-plugin:3.1.0:jsweet[m [1m(generate-js)[m @ [36mjsweet-quickstart[0;1m ---[m
[[1;34mINFO[m] maven version: 3.6.0
java.lang.NullPointerException: inStream parameter is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.base/java.util.Properties.load(Properties.java:403)
	at org.jsweet.JSweetConfig.<clinit>(JSweetConfig.java:48)
	at org.jsweet.JSweetMojo.execute(JSweetMojo.java:36)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[[1;34mINFO[m] JSweet transpiler version null (build date: null)
[[1;34mINFO[m] dependencies=[Dependency {groupId=org.jsweet, artifactId=jsweet-core, version=6.3.0, type=jar}, Dependency {groupId=org.jsweet.candies, artifactId=jquery, version=1.10.0-20170726, type=jar}]
[[1;34mINFO[m] candies detection: add project dependency Dependency {groupId=org.jsweet, artifactId=jsweet-core, version=6.3.0, type=jar} => org.jsweet:jsweet-core:jar:6.3.0:compile
[[1;34mINFO[m] candies detection: add project dependency Dependency {groupId=org.jsweet.candies, artifactId=jquery, version=1.10.0-20170726, type=jar} => org.jsweet.candies:jquery:jar:1.10.0-20170726:compile
[[1;34mINFO[m] all candies artifacts: [org.jsweet.candies:jquery:jar:1.10.0-20170726:compile (1; enabled), org.jsweet:jsweet-core:jar:6.3.0:compile (1; enabled)]
[[1;34mINFO[m] candies jars: [/home/alex/.m2/repository/org/jsweet/candies/jquery/1.10.0-20170726/jquery-1.10.0-20170726.jar, /home/alex/.m2/repository/org/jsweet/jsweet-core/6.3.0/jsweet-core-6.3.0.jar]
[[1;34mINFO[m] classpath from maven: /home/alex/.m2/repository/org/jsweet/candies/jquery/1.10.0-20170726/jquery-1.10.0-20170726.jar:/home/alex/.m2/repository/org/jsweet/jsweet-core/6.3.0/jsweet-core-6.3.0.jar
[[1;34mINFO[m] jsOut: /home/alex/jsweet-bugs/bug1/target/js
[[1;34mINFO[m] bundle: null
[[1;34mINFO[m] tsOut: /home/alex/jsweet-bugs/bug1/target/ts
[[1;34mINFO[m] tsOnly: null
[[1;34mINFO[m] tsserver: true
[[1;34mINFO[m] declarations: null
[[1;34mINFO[m] ignoreDefinitions: null
[[1;34mINFO[m] declarationOutDir: null
[[1;34mINFO[m] candiesJsOutDir: /home/alex/jsweet-bugs/bug1/webapp/candies
[[1;34mINFO[m] ecmaTargetVersion: ES6
[[1;34mINFO[m] moduleKind: none
[[1;34mINFO[m] sourceMap: null
[[1;34mINFO[m] sourceRoot: null
[[1;34mINFO[m] compileSourceRootsOverridenull
[[1;34mINFO[m] verbose: true
[[1;34mINFO[m] veryVerbose: null
[[1;34mINFO[m] jdkHome: /usr/lib/jvm/java-11-openjdk-amd64
[[1;34mINFO[m] factoryClassName: null
[[1;34mINFO[m] ignoredProblems: null
[[1;34mINFO[m] javaCompilerExtraOptions: null
[[1;34mINFO[m] extraSystemPath: null
2021-09-20 10:20:02.002 INFO  JSweetTranspiler:423 - no configuration file found at /home/alex/jsweet-bugs/bug1/jsweetconfig.json
2021-09-20 10:20:02.002 INFO  JSweetTranspiler:528 - creating transpiler version null (build date: null)
2021-09-20 10:20:02.002 INFO  JSweetTranspiler:530 - current dir: /home/alex/jsweet-bugs/bug1/.
2021-09-20 10:20:02.002 INFO  JSweetTranspiler:531 - base directory: /home/alex/jsweet-bugs/bug1
2021-09-20 10:20:02.002 INFO  JSweetTranspiler:532 - working directory: /home/alex/jsweet-bugs/bug1/.jsweet
2021-09-20 10:20:02.002 INFO  JSweetTranspiler:533 - tsOut: /home/alex/jsweet-bugs/bug1/target/ts - /home/alex/jsweet-bugs/bug1/target/ts
2021-09-20 10:20:02.002 INFO  JSweetTranspiler:534 - jsOut: /home/alex/jsweet-bugs/bug1/target/js - /home/alex/jsweet-bugs/bug1/target/js
2021-09-20 10:20:02.002 INFO  JSweetTranspiler:535 - candyJsOut: /home/alex/jsweet-bugs/bug1/webapp/candies
2021-09-20 10:20:02.002 INFO  JSweetTranspiler:536 - factory: org.jsweet.transpiler.JSweetFactory@387bf2d9
2021-09-20 10:20:02.002 DEBUG JSweetTranspiler:537 - compile classpath: /home/alex/jsweet-bugs/bug1/jsweet_extension:/home/alex/.m2/repository/org/jsweet/candies/jquery/1.10.0-20170726/jquery-1.10.0-20170726.jar:/home/alex/.m2/repository/org/jsweet/jsweet-core/6.3.0/jsweet-core-6.3.0.jar
2021-09-20 10:20:02.002 DEBUG JSweetTranspiler:538 - runtime classpath: /usr/share/maven/boot/plexus-classworlds-2.x.jar
2021-09-20 10:20:02.002 DEBUG JSweetTranspiler:539 - extension directory: /home/alex/jsweet-bugs/bug1/jsweet_extension
2021-09-20 10:20:02.002 INFO  CandyProcessor:123 - candies processor classpath: /home/alex/jsweet-bugs/bug1/jsweet_extension:/home/alex/.m2/repository/org/jsweet/candies/jquery/1.10.0-20170726/jquery-1.10.0-20170726.jar:/home/alex/.m2/repository/org/jsweet/jsweet-core/6.3.0/jsweet-core-6.3.0.jar
2021-09-20 10:20:02.002 INFO  CandyProcessor:141 - extracted candies directory: /home/alex/jsweet-bugs/bug1/webapp/candies
[[1;34mINFO[m] source includes: {}
[[1;34mINFO[m] source excludes: {}
[[1;34mINFO[m] sources paths: [/home/alex/jsweet-bugs/bug1/src/main/java]
[[1;34mINFO[m] sources paths from resources: [/home/alex/jsweet-bugs/bug1/src/main/java]
[[1;34mINFO[m] sourceFiles=[/home/alex/jsweet-bugs/bug1/src/main/java/quickstart/QuickStart.java]
2021-09-20 10:20:02.002 DEBUG ProcessUtil:67 - extra path: 
2021-09-20 10:20:02.002 INFO  ProcessUtil:138 - cannot find tsc - searching in /home/alex/.jsweet.v3-node_modules
[[1;31mERROR[m] transpilation failed
[1;31mjava.lang.NullPointerException[m
    [1mat[m org.jsweet.transpiler.candy.CandyProcessor.checkCandyVersion ([1mCandyProcessor.java:247[m)
    [1mat[m org.jsweet.transpiler.candy.CandyProcessor.getCandiesDescriptorsFromClassPath ([1mCandyProcessor.java:219[m)
    [1mat[m org.jsweet.transpiler.candy.CandyProcessor.processCandies ([1mCandyProcessor.java:159[m)
    [1mat[m org.jsweet.transpiler.JSweetTranspiler.transpile ([1mJSweetTranspiler.java:821[m)
    [1mat[m org.jsweet.transpiler.JSweetTranspiler.transpile ([1mJSweetTranspiler.java:794[m)
    [1mat[m org.jsweet.AbstractJSweetMojo.transpile ([1mAbstractJSweetMojo.java:681[m)
    [1mat[m org.jsweet.JSweetMojo.execute ([1mJSweetMojo.java:43[m)
    [1mat[m org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo ([1mDefaultBuildPluginManager.java:137[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:210[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:156[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:148[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([1mLifecycleModuleBuilder.java:117[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([1mLifecycleModuleBuilder.java:81[m)
    [1mat[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build ([1mSingleThreadedBuilder.java:56[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute ([1mLifecycleStarter.java:128[m)
    [1mat[m org.apache.maven.DefaultMaven.doExecute ([1mDefaultMaven.java:305[m)
    [1mat[m org.apache.maven.DefaultMaven.doExecute ([1mDefaultMaven.java:192[m)
    [1mat[m org.apache.maven.DefaultMaven.execute ([1mDefaultMaven.java:105[m)
    [1mat[m org.apache.maven.cli.MavenCli.execute ([1mMavenCli.java:956[m)
    [1mat[m org.apache.maven.cli.MavenCli.doMain ([1mMavenCli.java:288[m)
    [1mat[m org.apache.maven.cli.MavenCli.main ([1mMavenCli.java:192[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 ([1mNative Method[m)
    [1mat[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke ([1mNativeMethodAccessorImpl.java:62[m)
    [1mat[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke ([1mDelegatingMethodAccessorImpl.java:43[m)
    [1mat[m java.lang.reflect.Method.invoke ([1mMethod.java:566[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced ([1mLauncher.java:282[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.launch ([1mLauncher.java:225[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode ([1mLauncher.java:406[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.main ([1mLauncher.java:347[m)
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1;31mBUILD FAILURE[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] Total time:  3.138 s
[[1;34mINFO[m] Finished at: 2021-09-20T10:20:02+02:00
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;31mERROR[m] Failed to execute goal [32morg.jsweet:jsweet-maven-plugin:3.1.0:jsweet[m [1m(generate-js)[m on project [36mjsweet-quickstart[m: [1;31mtranspilation failed[m: NullPointerException -> [1m[Help 1][m
[[1;31mERROR[m] 
[[1;31mERROR[m] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.
[[1;31mERROR[m] Re-run Maven using the [1m-X[m switch to enable full debug logging.
[[1;31mERROR[m] 
[[1;31mERROR[m] For more information about the errors and possible solutions, please read the following articles:
[[1;31mERROR[m] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Workaround 1:
```bash
$rm -r  ~/.m2/repository/org/jsweet/jsweet-transpiler
```
Workaround 2:
```bash
$unzip jsweet-quickstart-master.zip
$cd jsweet-quickstart-master
$grep jsweet.transpiler.version.3 pom.xml
		<jsweet.transpiler.version>3.1.0</jsweet.transpiler.version>
#patch pom.xml
$grep sweet.transpiler.version.3 pom.xml
		<jsweet.transpiler.version>3.2.0-SNAPSHOT</jsweet.transpiler.version>
```

**Comment by lgrignon** [comment]
We apologize for the inconvenience.
It logs "cannot find tsc", is tsc executable findable in /home/alex/.jsweet.v3-node_modules ? 

Typescript is installed automatically by JSweet, but maybe something went wrong on your machine

**Comment by lgrignon** [comment]
Is Node installed? Which version please?

**Comment by AlexGeller1** [comment]
No problem. Tsc seems to be there (cleaned the directory before compiling) and node is version v10.15.2:
```bash
find  ~/.jsweet.v3-node_modules -name  tsc
/home/alex/.jsweet.v3-node_modules/node_modules/typescript/bin/tsc
/home/alex/.jsweet.v3-node_modules/node_modules/.bin/tsc
$node --version
v10.15.2
```

**Comment by lgrignon** [comment]
Could you please try again with 3.2.0 SNAPSHOT (forcing dep refresh). I deployed a possible fix :)

**Comment by AlexGeller1** [comment]
That fixed it! Thanks for your very timely responses on this and other issues. That is very much appreciated by us.

**Comment by lgrignon** [comment]
You are welcome :)
